# Generated by Django 4.2.7 on 2026-02-18 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='Email покупателя')),
                ('selected_course', models.CharField(max_length=50, verbose_name='Выбранный курс')),
                ('has_chat', models.BooleanField(default=False, verbose_name='Доступ к чату')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Payment Intent ID')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Checkout Session ID')),
                ('amount_total', models.IntegerField(default=0, verbose_name='Общая сумма (центы)')),
                ('amount_received', models.IntegerField(default=0, verbose_name='Получено (центы)')),
                ('currency', models.CharField(default='usd', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'Обработка'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='main_paymen_email_5230f5_idx'), models.Index(fields=['stripe_payment_intent_id'], name='main_paymen_stripe__777aaa_idx'), models.Index(fields=['stripe_checkout_session_id'], name='main_paymen_stripe__4521e3_idx'), models.Index(fields=['status'], name='main_paymen_status_a07f84_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('course_level', models.IntegerField(default=1, verbose_name='Уровень курса')),
                ('has_chat_access', models.BooleanField(default=False, verbose_name='Доступ к чату')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Активирован')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('discord_invite_link', models.URLField(blank=True, null=True, verbose_name='Ссылка Discord')),
                ('discord_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Discord User ID')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_access', to='main.payment', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Доступ к курсу',
                'verbose_name_plural': 'Доступы к курсам',
                'ordering': ['-activated_at'],
                'indexes': [models.Index(fields=['email'], name='main_course_email_528081_idx'), models.Index(fields=['is_active'], name='main_course_is_acti_dee816_idx'), models.Index(fields=['course_level'], name='main_course_course__7aada0_idx')],
            },
        ),
    ]
